import DarkModeProvider from "@/components/DarkModeProvider";
import Navbar from "@/components/Navbar";
import "@/assets/styles/globals.css";
import { ContextProvider } from "@/store/user-context";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function AccountLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ContextProvider>
      <DarkModeProvider>
        <Navbar />
        {children}
      </DarkModeProvider>
    </ContextProvider>
  );
}
