import "@/assets/styles/globals.css";
import fav from "./favicon.ico";

export const metadata = {
  icons: {
    icon: fav.src,
  },
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="dark:bg-gray-900">{children}</body>
    </html>
  );
}
