import DarkModeProvider from "@/components/DarkModeProvider";
import DarkModeToggle from "@/components/DarkModeToggle";
import "@/assets/styles/globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <DarkModeProvider>
      <nav>
        <DarkModeToggle />
      </nav>
      {children}
    </DarkModeProvider>
  );
}
